const bookmarks = [
  {
    title: "Work",
    links: [
      { name: "EricNgigi(website)", url: "https://ericngigi.com" },
      { name: "Linkedin(ErikNgigi)", url: "https://www.linkedin.com/in/eric-ngigi-073b72153/" },
      { name: "GitHub(ErikNgigi)", url: "https://github.com/ErikNgigi" },
      { name: "Netlify(ErikNgigi)", url: "https://app.netlify.com/teams/erikngigi/overview" },
      { name: "Hugo(Local)", url: "http://localhost:1313" },
      { name: "AWS(DrawIO)", url: "https://app.diagrams.net/?splash=0&libs=aws4" },
      { name: "AWS(Certification)", url: "https://www.aws.training/Certification" },
      { name: "AWS(SkillBuilder)", url: "https://explore.skillbuilder.aws/pages/16/learner-dashboard" },
    ],
  },
  {
    title: "Personal Interest",
    links: [
      { name: "YouTube", url: "https://youtube.com" },
      { name: "Pahe", url: "https://pahe.li" },
      { name: "Nyaa(Torrent)", url: "https://nyaa.si/" },
      { name: "GogoAnime", url: "https://gogoanimehd.io/" },
      { name: "Piratebay(Torrent)", url: "https://thepiratebay.org/index.html" },
      { name: "1337x(Torrent)", url: "https://1337x.to/" },
      { name: "Animelool(index)", url: "https://animelool.com/Anime/" },
    ],
  },
  {
    title: "Productivity",
    links: [
      { name: "EricWanyoike", url: "https://mail.google.com/mail/u/?authuser=ericwanyoike@gmail.com" },
      { name: "EricMosesNgigi", url: "https://mail.google.com/mail/u/?authuser=ericmosesngigi@gmail.com" },
      { name: "EricWanyoike772", url: "https://mail.google.com/mail/u/?authuser=ericwanyoike772@gmail.com" },
      { name: "EricTheGiggs", url: "https://mail.google.com/mail/u/?authuser=ericthegiggs@gmail.com" },
      { name: "Google Drive", url: "https://drive.google.com/drive/u/0/my-drive" },
      { name: "Google Docs", url: "https://docs.google.com/document/u/0/" },
      { name: "Google Sheets", url: "https://docs.google.com/spreadsheets/u/0/" },
      { name: "GitHub", url: "https://github.com/ErikNgigi" },
    ],
  },
  {
    title: "Resources",
    links: [
      { name: "ChatGpt", url: "https://chat.openai.com/" },
      { name: "ArchWiki", url: "https://wiki.archlinux.org/" },
      { name: "OdinProject(TOP)", url: "https://www.theodinproject.com/dashboard" }, 
      { name: "AfricaLeaders(ALX)", url: "https://member.theroom.com/alx/" },
      { name: "W3Schools", url: "https://my-learning.w3schools.com/" },
      { name: "HackerRank", url: "https://www.hackerrank.com/" },
      { name: "RealPython", url: "https://realpython.com/" },
      { name: "ATBS(Python)", url: "https://automatetheboringstuff.com/" },
      { name: "JavaScriptInfo", url: "https://javascript.info/" },
      { name: "Cpanel", url: "https://exams.cpanel.net/dashboard" },
    ],
  },
];
